%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name basic_vert_spv -V shaders/basic.vert -o ref_vk/spirv/basic_vert.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name basic_frag_spv -V shaders/basic.frag -o ref_vk/spirv/basic_frag.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name basic_color_quad_vert_spv -V shaders/basic_color_quad.vert -o ref_vk/spirv/basic_color_quad_vert.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name basic_color_quad_frag_spv -V shaders/basic_color_quad.frag -o ref_vk/spirv/basic_color_quad_frag.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name nullmodel_vert_spv -V shaders/nullmodel.vert -o ref_vk/spirv/nullmodel_vert.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name nullmodel_frag_spv -V shaders/nullmodel.frag -o ref_vk/spirv/nullmodel_frag.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name model_vert_spv -V shaders/model.vert -o ref_vk/spirv/model_vert.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name model_frag_spv -V shaders/model.frag -o ref_vk/spirv/model_frag.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name particle_vert_spv -V shaders/particle.vert -o ref_vk/spirv/particle_vert.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name particle_frag_spv -V shaders/particle.frag -o ref_vk/spirv/particle_frag.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name point_particle_vert_spv -V shaders/point_particle.vert -o ref_vk/spirv/point_particle_vert.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name point_particle_frag_spv -V shaders/point_particle.frag -o ref_vk/spirv/point_particle_frag.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name sprite_vert_spv -V shaders/sprite.vert -o ref_vk/spirv/sprite_vert.c
%VULKAN_SDK%\bin32\glslangValidator.exe --variable-name sprite_frag_spv -V shaders/sprite.frag -o ref_vk/spirv/sprite_frag.c
