# vkQuake2 for MacOS

debug:
	xcodebuild -workspace vkQuake2.xcworkspace -scheme vkQuake2 -configuration Debug build
release:
	xcodebuild -workspace vkQuake2.xcworkspace -scheme vkQuake2 -configuration Release build
clean:
	xcodebuild -workspace vkQuake2.xcworkspace -scheme vkQuake2 -configuration Debug clean
	xcodebuild -workspace vkQuake2.xcworkspace -scheme vkQuake2 -configuration Release clean

.PHONY: debug release clean
