name: Linux
on:
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install required packages
        shell: bash
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y yad make gcc g++ mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev libxext-dev libfuse2
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          version: 1.4.350.0
          install_runtime: false
          cache: true
          stripdown: true
      - name: Build vkQuake2 Debug
        shell: bash
        run: |
          cd linux
          make clean debug
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vkQuake2-Ubuntu-debug-x64
          path: |
            linux/debugx64
            !linux/debugx64/**/*.o
      - name: Build vkQuake2 Release
        shell: bash
        run: |
          cd linux
          make clean release
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vkQuake2-Ubuntu-release-x64
          path: |
            linux/releasex64
            !linux/releasex64/**/*.o

      - name: Build vkQuake2 appImage
        shell: bash
        run: |
           linux/appimage/appimage.sh
      - name: Upload vkQuake2 AppImage artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vkQuake2-AppImage
          path: |
            vkQuake.AppImage
