name: MacOS
on:
  push:
    branches:
      - master

jobs:
  MacOS:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v7
      
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          vulkan_version: 1.4.350.1
          install_runtime: false
          cache: true
          stripdown: true
      - name: Build vkQuake2 Debug
        run: |
          cd macos
          make clean-xcode debug-xcode
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vkQuake2-MacOS-debug-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
      - name: Build vkQuake2 Release
        run: |
          cd macos
          make clean-xcode release-xcode
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vkQuake2-MacOS-release-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
