name: MacOS
env:
  VK_VERSION: 1.4.350.1
on:
  push:
    branches:
      - master

jobs:
  MacOS:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v7
      
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@0ef43dbc8af56d77bcb1e8b1ebbbaa8718ead524
        with:
          version: $VK_VERSION
          cache: true
      - name: Build vkQuake2 Debug
        run: |
          cd macos
          make clean-xcode debug-xcode
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vkQuake2-MacOS-debug-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
      - name: Build vkQuake2 Release
        run: |
          cd macos
          make clean-xcode release-xcode
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vkQuake2-MacOS-release-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
